// <auto-generated />
using System;
using GeoSupport_ms.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeoSupport_ms.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeoSupport_ms.Models.Color", b =>
                {
                    b.Property<int>("Id_color")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HexCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Name")
                        .HasColumnType("float");

                    b.HasKey("Id_color");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("GeoSupport_ms.Models.Color_Flag", b =>
                {
                    b.Property<int>("Id_color")
                        .HasColumnType("int");

                    b.Property<int>("Id_flag")
                        .HasColumnType("int");

                    b.Property<int>("order")
                        .HasColumnType("int");

                    b.HasKey("Id_color", "Id_flag");

                    b.HasIndex("Id_flag");

                    b.ToTable("Color_Flag");
                });

            modelBuilder.Entity("GeoSupport_ms.Models.Continent", b =>
                {
                    b.Property<int>("Id_continent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id_continent");

                    b.ToTable("Continent");
                });

            modelBuilder.Entity("GeoSupport_ms.Models.Country", b =>
                {
                    b.Property<int>("Id_country")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Capital")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ContinentId_continent")
                        .HasColumnType("int");

                    b.Property<int?>("FlagId_flag")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("MapImage")
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id_country");

                    b.HasIndex("ContinentId_continent");

                    b.HasIndex("FlagId_flag");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("GeoSupport_ms.Models.Flag", b =>
                {
                    b.Property<int>("Id_flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FlagImage")
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id_flag");

                    b.ToTable("Flag");
                });

            modelBuilder.Entity("GeoSupport_ms.Models.Place", b =>
                {
                    b.Property<int>("Id_place")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryId_country")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PlaceImage")
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id_place");

                    b.HasIndex("CountryId_country");

                    b.ToTable("Place");
                });

            modelBuilder.Entity("GeoSupport_ms.Models.Color_Flag", b =>
                {
                    b.HasOne("GeoSupport_ms.Models.Color", "Color")
                        .WithMany("Color_Flags")
                        .HasForeignKey("Id_color")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoSupport_ms.Models.Flag", "Flag")
                        .WithMany("Color_Flags")
                        .HasForeignKey("Id_flag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoSupport_ms.Models.Country", b =>
                {
                    b.HasOne("GeoSupport_ms.Models.Continent", null)
                        .WithMany("Countries")
                        .HasForeignKey("ContinentId_continent");

                    b.HasOne("GeoSupport_ms.Models.Flag", "Flag")
                        .WithMany()
                        .HasForeignKey("FlagId_flag");
                });

            modelBuilder.Entity("GeoSupport_ms.Models.Place", b =>
                {
                    b.HasOne("GeoSupport_ms.Models.Country", null)
                        .WithMany("Places")
                        .HasForeignKey("CountryId_country");
                });
#pragma warning restore 612, 618
        }
    }
}
